name: Gradle Build

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: windows-latest  # Используем windows-latest для запуска на Windows
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'

    - name: Cache Gradle dependencies
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Download and install ChromeDriver
      run: |
        # Скачиваем chromedriver
        CHROME_DRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
        wget https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_win32.zip
        unzip chromedriver_win32.zip

        # Перемещаем chromedriver в System32
        move chromedriver.exe C:\Windows\System32
        chromedriver --version  # Печатаем версию для проверки
    
    - name: Grant execute permission to gradlew
      run: chmod +x gradlew

    - name: Install dependencies and run tests
      run: ./gradlew test --info
