name: Gradle Selenide Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build and test
      run: ./gradlew clean test

    - name: Run JAR file
      run: java -jar ./artifacts/app-card-delivery.jar
